import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useSession, signIn, signOut } from "next-auth/react"

export default function Home() {

  // const [session, loading] = useSession();

  return (
    <div className="bg-black flex items-center justify-center min-h-screen"
    style={{
      'background-image':
        'linear-gradient(rgb(0 0 0 / 80%), rgb(0 0 0 / 80%)), url(/netflixhero.jpeg)',
    }}
    >
      <Head>
        <title>Netflix Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500&display=swap"
          rel="stylesheet"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col items-center justify-center flex-1 px-2">
        <h1 className="text-4xl font-bold text-white text-center max-w-lg">
          Unlimited movies, TV shows, and more.
        </h1>
        <h2 className="text-2xl text-white mt-4 mb-8">Watch anywhere. Cancel anytime</h2>
        <p className="text-white text-lg">Ready to watch? Enter your email to create or restart your membership</p>
        <div className="flex  mt-4">
          <input className="bg-white p-4 min-w-[400px] " placeholder="Email adress"/>
          <button className="flex items-center  bg-[#e50914] px-8 text-white ">Get Started 
            <svg class="w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"></path>
            </svg>
          </button>
        </div>
      </main>

      
    </div>
  )
}
